### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by Marabushka** [ArkhipenkaPiotr/thanos_snap_effect#9] opened 2024-12-12 05:07 UTC
thanos_snap_effect: ^0.0.8
flutter: 3.24.3

Problem Description
When using the DeleteAnimatedContainer widget with the thanos_snap_effect package, I encounter the following error after the afterAnimation callback removes the item from the list:

```
flutter: SHOUT: 2024-12-12 10:02:25.144586 Unhandled exception setState() called after dispose(): _ShaderBuilderState#218b4(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
flutter: #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
#2      _ShaderBuilderState._initShader (package:thanos_snap_effect/src/shader_builder.dart:62:5)
<asynchronous suspension>
```

Here is my code sample: 

```
class DeleteAnimatedContainer extends StatefulWidget {
  const DeleteAnimatedContainer({
    super.key,
    required this.needAnimate,
    required this.afterAnimation,
    this.wipeDuration = const Duration(milliseconds: 1500),
    this.scaleDuration = const Duration(milliseconds: 750),
    required this.child,
  });

  final Duration wipeDuration;
  final Duration scaleDuration;
  final bool needAnimate;
  final VoidCallback afterAnimation;
  final Widget child;

  @override
  State<DeleteAnimatedContainer> createState() => _DeleteAnimatedContainerState();
}

class _DeleteAnimatedContainerState extends State<DeleteAnimatedContainer> with TickerProviderStateMixin {
  late final AnimationController _controller;
  late final AnimationController _scaleController;
  late final Animation<double> _scaleAnimation;

  @override
  void dispose() {
    _controller.dispose();
    _scaleController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: widget.wipeDuration,
      vsync: this,
    );

    _scaleController = AnimationController(
      duration: widget.scaleDuration,
      vsync: this,
    );

    _scaleAnimation = Tween<double>(begin: 1.0, end: 0.0).animate(
      CurvedAnimation(
        parent: _scaleController,
        curve: Curves.easeInOut,
      ),
    );
  }

  @override
  void didUpdateWidget(covariant DeleteAnimatedContainer oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.needAnimate == oldWidget.needAnimate) return;

    if (widget.needAnimate && mounted) {
      _startAnimation();
    }
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      builder: (_, __) {
        return SizeTransition(
          sizeFactor: _scaleAnimation,
          axis: Axis.vertical,
          child: Snappable(
            animation: _controller.view,
            child: widget.child,
          ),
        );
      },
    );
  }

  void _startAnimation() {
    _controller.forward().then((_) => widget.afterAnimation());
    _scaleController.forward();
  }
}

```

I think the problem is in `lib/src/shader_builder.dart` in  `_initShader()` func, maybe add mounted check before setState() ?

**Comment by ArkhipenkaPiotr** [comment] 2024-12-12 07:54
It looks strange since the _initShader is usually called during the Snappable widget initialization. @Marabushka Could you please provide a code sample of using the DeleteAnimatedContainer widget?

**Comment by Marabushka** [comment] 2024-12-12 07:56
@ArkhipenkaPiotr 
```
InfinityScrollListener(
        onStartReached: onStartReached,
        onEndReached: onEndReached,
        child: ScrollablePositionedList.builder(
          itemScrollController: itemScrollController,
          itemPositionsListener: itemPositionsListener,
          reverse: true,
          itemCount: count,
          padding: EdgeInsets.only(bottom: 12.0, top: topMargin + 12.0),
          itemBuilder: (context, index) {
            if (index == messageList.length) {
              return const MessageInProgressListTile();
            }
            final message = messageList[index];
            final operations = message.operations(
              messageDeletionAbilityTimeout: messageDeletionAbilityTimeout,
              streamOwner: stream is StreamWithMultipleUsers ? stream.owner : null,
            );

            final messageTile = MessageListTile(
              stream: stream,
              message: message,
              onReplyTap: onReplyTap,
              onOpenGallery: onOpenGallery,
              lastReadId: lastReadId,
              jumpFromId: jumpFromId,
              jumpToId: jumpToId,
              previousMessage: index < messageList.length - 1 ? messageList[index + 1] : null,
              nextMessage: index > 0 ? messageList[index - 1] : null,
              onForwardedTap: message is Message && message.originalMessage?.owner is! UserGuest
                  ? () => onForwardedTap(message.forwardStreamId, message.forwardSenderId)
                  : null,
              onOpenUserProfile: onOpenUserProfile,
              onRetry: message is MessageDraft && message.status.isUndelivered ? () => onRetrySend(message) : null,
              onCancel: message is MessageDraft ? () => onCancelSend(message) : null,
              onDelete: operations.contains(MessageOperation.delete) ? onDelete : null,
              onCopy: onCopy,
              onEdit: onEdit,
              onReply: onReply,
              onForward: onForward,
              onEntityLinkTap: onEntityLinkTap,
              onMentionTap: onMentionTap,
              onUrlTap: onUrlTap,
              onPopupShow: (overlay) {
                FocusScope.of(context).requestFocus(FocusNode());
                onPopupShow(overlay);
              },
              onPopupClose: onPopupClose,
              onMeet: onMeet,
              onMeetDownloaded: onMeetDownloaded,
              onJumpToIdCompleted: onJumpToIdCompleted,
              padding: _getSeparatorValue(index),
              messageEditingAbilityTimeout: messageEditingAbilityTimeout,
            );

            return message is Message
                ? DeleteAnimatedContainer(
                    key: ValueKey(message.id),
                    needAnimate: message.id == needDeleteMessage,
                    afterAnimation: () => onDeleteComplete != null ? onDeleteComplete(message.id) : null,
                    child: messageTile,
                  )
                : messageTile;
          },
        ),
      ),
    );
  }
  ```

**Comment by ArkhipenkaPiotr** [comment] 2024-12-12 07:59
There are a lot of context variables, please provide a full file to reproduce it @Marabushka

**Comment by Marabushka** [comment] 2024-12-12 08:26
@ArkhipenkaPiotr 
Due to our privacy policy, I am unable to share the exact implementation. However, I managed to resolve the issue by limiting the rebuilding of the `DeleteAnimatedContainer` widget in my application.

That being said, I still believe it would be beneficial to add a mounted check in the `_initShader()` function. Since `_initShader()`  involves asynchronous operations, there is a possibility that the widget might be disposed of before the operation completes. Adding this check would make the implementation more robust and prevent similar issues in the future.

**Comment by ArkhipenkaPiotr** [comment] 2024-12-14 15:39
@Marabushka The fix has been pushed to master, thank you for the suggestion.

**Closed as completed by ArkhipenkaPiotr** 2024-12-14 15:39 UTC
